# Travis CI configuration file for replisome

dist: trusty
sudo: required
language: python

services:
  - docker

python:
  - 2.7

env:
  global:
    - COMPOSE_FILE=tests/build/docker-compose.yml
  matrix:
    - {PY_VER: 2.7, PG_VER: 9.4}
    - {PY_VER: 2.7, PG_VER: 9.5}
    - {PY_VER: 2.7, PG_VER: 9.6}
    - {PY_VER: 3.5, PG_VER: 9.4}
    - {PY_VER: 3.5, PG_VER: 9.5}
    - {PY_VER: 3.5, PG_VER: 9.6}


install:
  - sudo pip install -q "ansible>=2.4"
  - ansible-playbook tests/playbook.yml -e pg_ver=${PG_VER} -e py_ver=${PY_VER}
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose run --rm
      -e PGHOST=master -e PGUSER=postgres
      test make installcheck
  - docker-compose run --rm
      -e RS_TEST_SRC_DSN="host=master user=postgres"
      -e RS_TEST_TGT_DSN="host=slave user=postgres"
      test py.test -v

notifications:
  email: false
