# Travis CI configuration file for replisome

dist: trusty
sudo: required
language: python

services:
  - docker

python:
  - 2.7

env:
  global:
    - COMPOSE_FILE=tests/build/docker-compose.yml
  matrix:
    - {PY_VER: 2.7, PG_VER: 9.4}
    - {PY_VER: 2.7, PG_VER: 9.5}
    - {PY_VER: 2.7, PG_VER: 9.6}
    - {PY_VER: 3.5, PG_VER: 9.4}
    - {PY_VER: 3.5, PG_VER: 9.5}
    - {PY_VER: 3.5, PG_VER: 9.6}

before_install:
  - sudo pip install -q "ansible>=2.4"

install:
  - ansible-playbook tests/playbook.yml -e pg_ver=${PG_VER} -e py_ver=${PY_VER}
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose run --rm test make installcheck
  - docker-compose run --rm test py.test -v

after_script:
  - docker-compose down

notifications:
  email: false
